### ISSUE TITLE
any plans for whole-content drawing support of UIWebView?

### ISSUE THREAD

**Issue by gmarzloff** [sgr-ksmt/PDFGenerator#18]
Hi, 
This software is wonderfully easy to use. However, I need to export UIWebView -> PDF.  Do you have any plans to support UIWebView so that the content is not cropped to what is visible on-screen?

Thanks

**Comment by sgr-ksmt** [comment]
HI @gmarzloff ,
I think this library can export `UIWebView`'s whole-content to PDF because `UIWebView` is a subclass of `UIScrollView` and this library is compatible with exporting `UIScrollView`'s whole-content.

If you try (or have already tried) and not working perfectly,
please let me know again. :cry:

Thanks.

**Comment by gmarzloff** [comment]
Hi,
I thought it would work because it's a subclass of `UIScrollView` but I am not getting the right result. 
```
func generatePDFAndSaveToFile(sourceView : UIWebView){
        do{
            try PDFGenerator.generate([sourceView], outputPath: self.path)
        }catch (let error) {
            print(error)
        }
    }
```
This generates the pdf file but clips to the visible frame.

**Comment by sgr-ksmt** [comment]
@gmarzloff 

I tried exporting UIWebView and got wrong result... sorry :cry: 

I'll fix this problem and release new version in a few hours.
Please wait a little while more.

**Comment by sgr-ksmt** [comment]
@gmarzloff 
I’m sorry to have kept you waiting. 
I have fixed this problem and just release _v1.1.3_ .
Please re-install this library!
